services:
  - type: web
    name: student-management-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: student-management-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: build
    rootDir: frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
