services:
  - type: web
    name: student-management-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: student-management-frontend
    env: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
